version: '3.9'
services:
  app:
    image: monitor-app
    build:
      context: ./monitor
      dockerfile: Dockerfile
      target: runner
    volumes:
      - /app/public
    ports:
      - "3000:3000"
